name: server
description: Backend for upcrash
dependencies:
  uri: "^0.11.1"
  convert: "^2.0.0"
  test: "^1.3.0"
  logging: "^0.11.3+1"
  firebase: "^5.0.1"
  http: "^0.11.3+16"
  googleapis_auth: "^0.2.3+2"
  mime: "^0.9.6+2"
  mailer: "^1.1.4"
