name: server
description: Backend for upcrash
dependencies:
  uri:
    git: git://github.com/google/uri.dart.git
  convert: "^2.0.0"
  test: "^0.12.29+1"
  mockito: "^2.2.1"
  logging: "^0.11.3+1"
  firebase: '^4.3.0'
  http: "^0.11.3+16"
  googleapis_auth: "^0.2.3+2"
  mime_type: "^0.2.1"
  mailer: "^1.1.4"
